name:                real-world-haskell-exercises
version:             0.1.0.0
github:              "DestyNova/real-world-haskell-exercises"
license:             MIT
author:              "Oisín Mac Fhearaí"
maintainer:          "denpashogai@gmail.com"
copyright:           "2021 Oisín Mac Fhearaí"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/DestyNova/real-world-haskell-exercises#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  real-world-haskell-exercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-exercises

tests:
  real-world-haskell-exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - real-world-haskell-exercises
    - hspec
